# TO DO TASK1

In [ ]:
import pandas as pd

# Read the dataset (replace 'your_dataset.csv' with your actual dataset path)
df = pd.read_csv('/content/drive/MyDrive/student.csv')

# Observe the first few rows
print(df.head())


   Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62


In [ ]:
# Print top 5 rows
print("Top 5 rows:")
print(df.head())

# Print bottom 5 rows
print("Bottom 5 rows:")
print(df.tail())


Top 5 rows:
   Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62
Bottom 5 rows:
     Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72


In [ ]:
# Get concise information about the dataset
print("Dataset Information:")
df.info()


Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB


In [ ]:
# Get descriptive statistics for the numerical columns
print("Descriptive Statistics:")
print(df.describe())


Descriptive Statistics:
              Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      68.000000    70.000000    69.500000
75%      78.000000    81.000000    79.000000
max     100.000000   100.000000   100.000000


In [ ]:
# Split the dataset into Features (X) and Label (Y)
X = df.drop(columns=['Math'])  # Features: Reading and Writing
Y = df['Math']  # Label: Math

# Print the shapes of X and Y to confirm
print("Shape of X (Features):", X.shape)
print("Shape of Y (Label):", Y.shape)


Shape of X (Features): (1000, 2)
Shape of Y (Label): (1000,)


# TO DO TASK2

In [ ]:
import numpy as np

# Number of features (d) - based on your dataset (Reading and Writing are features)
d = X.shape[1]  # In this case, X has 2 features (Reading and Writing)

# Initialize W with random values (just as an example)
W = np.random.rand(d, 1)  # W is a d x 1 vector
print("Weight Vector W:")
print(W)


Weight Vector W:
[[0.87768267]
 [0.7553612 ]]


In [ ]:
# Feature matrix X: 2 features (Reading and Writing) and 5 samples
X = df[['Reading', 'Writing']].T  # Transpose to get the shape (d x n)
X = X.values  # Convert to numpy array
print("Feature Matrix X:")
print(X)


Feature Matrix X:
[[68 81 80 ... 87 82 66]
 [63 72 78 ... 94 78 72]]


In [ ]:
# Output vector Y: target values for Math
Y = df['Math'].values.reshape(-1, 1)  # Reshape to make it a column vector (n x 1)
print("Output Vector Y:")
print(Y)


Output Vector Y:
[[ 48]
 [ 62]
 [ 79]
 [ 76]
 [ 59]
 [ 69]
 [ 70]
 [ 46]
 [ 61]
 [ 86]
 [ 62]
 [ 72]
 [ 56]
 [ 81]
 [ 61]
 [ 49]
 [ 60]
 [ 45]
 [ 71]
 [ 75]
 [ 66]
 [ 57]
 [ 67]
 [ 63]
 [ 68]
 [ 68]
 [ 62]
 [ 56]
 [ 82]
 [ 64]
 [ 71]
 [ 69]
 [ 64]
 [ 76]
 [ 61]
 [ 47]
 [ 50]
 [ 75]
 [ 69]
 [ 42]
 [ 73]
 [ 78]
 [ 65]
 [ 51]
 [ 61]
 [ 69]
 [ 51]
 [ 64]
 [ 90]
 [ 58]
 [100]
 [ 73]
 [ 62]
 [ 45]
 [ 47]
 [ 53]
 [ 62]
 [ 49]
 [ 77]
 [ 70]
 [ 60]
 [ 82]
 [100]
 [ 72]
 [ 62]
 [ 87]
 [ 56]
 [ 96]
 [ 68]
 [ 66]
 [ 68]
 [ 59]
 [ 52]
 [ 60]
 [ 60]
 [ 46]
 [ 62]
 [ 30]
 [ 83]
 [ 69]
 [ 82]
 [ 64]
 [ 57]
 [ 71]
 [ 37]
 [ 69]
 [ 72]
 [ 73]
 [ 70]
 [ 75]
 [ 54]
 [ 71]
 [ 60]
 [ 81]
 [ 58]
 [ 54]
 [ 49]
 [ 64]
 [ 84]
 [ 84]
 [ 33]
 [ 51]
 [ 68]
 [ 32]
 [ 43]
 [ 73]
 [ 82]
 [ 47]
 [ 74]
 [ 36]
 [ 58]
 [ 68]
 [ 92]
 [ 75]
 [ 43]
 [ 68]
 [ 49]
 [ 69]
 [ 91]
 [ 83]
 [ 65]
 [ 79]
 [ 74]
 [ 81]
 [ 41]
 [ 48]
 [ 31]
 [ 53]
 [ 87]
 [ 94]
 [ 77]
 [ 57]
 [ 64]
 [ 55]
 [ 61]
 [ 78]
 [ 94]
 [ 88]
 [ 77]
 [ 90]
 [ 

In [ ]:
# Compute the predicted Y values
Y_pred = np.dot(W.T, X)
print("Predicted Values (Y_pred):")
print(Y_pred)


Predicted Values (Y_pred):
[[107.27017755 125.47830313 129.13278767 132.5211969  103.00408566
  137.93104678 136.42032438  73.09857763 128.88814473 126.62206112
  108.90322143 145.21858349  72.60929174 126.62206112 114.31307132
   73.36465295 119.7229212   75.36466124 143.19714282 120.21220709
   90.93973879 107.78089581 119.84524267  82.65219794 138.93105093
  141.68642042 109.29161822 115.68003988 126.62206112 130.88815302
  123.47829484 141.68642042 119.33452442 109.65858263  70.73160492
  103.39248244  84.28524182 127.25510085 116.31307961  73.36465295
  141.31945601 120.45685003 100.49335911  83.04059473 114.06842837
  119.84524267  84.28524182 123.11133043 163.30438759 126.13277524
  163.30438759 143.83018255 130.01047035  81.01915407  81.6521938
   76.24234391  84.52988476  76.36466538 111.16930504 130.01047035
   92.08349678 149.48467538 155.50613263 131.76583569  69.46552546
  144.95250817 114.82378958 135.5426417   98.73799376  94.7165448
   98.86031523  93.32814387  78.38610

TO DO TASK3

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

# Assuming the data is already loaded in `df` as:
# df = pd.DataFrame({'Math': [48, 62, 79, 76, 59], 'Reading': [68, 81, 80, 83, 64], 'Writing': [63, 72, 78, 79, 62]})

# Features (X) and Target (Y)
X = df[['Reading', 'Writing']].values  # Features: Reading and Writing
Y = df['Math'].values.reshape(-1, 1)  # Target: Math scores

# Step 1: Split the dataset into training and test sets (80% training, 20% testing)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Print the shapes of the splits to confirm
print("Training Features (X_train) shape:", X_train.shape)
print("Testing Features (X_test) shape:", X_test.shape)
print("Training Labels (Y_train) shape:", Y_train.shape)
print("Testing Labels (Y_test) shape:", Y_test.shape)

# Step 2: Create the Weight Vector W (d x 1) for linear regression
d = X.shape[1]  # Number of features (Reading and Writing)
W = np.random.rand(d, 1)  # Initialize W with random values

# Step 3: Compute the predicted Y values (Y_pred) using W^T * X
Y_pred_train = np.dot(X_train, W)  # Prediction for training data
Y_pred_test = np.dot(X_test, W)  # Prediction for test data

# Print the matrices and predictions
print("\nFeature Matrix X (Training):")
print(X_train)
print("Feature Matrix X (Testing):")
print(X_test)

print("\nWeight Vector W:")
print(W)

print("\nPredicted Y values (Training):")
print(Y_pred_train)

print("\nPredicted Y values (Testing):")
print(Y_pred_test)


Training Features (X_train) shape: (800, 2)
Testing Features (X_test) shape: (200, 2)
Training Labels (Y_train) shape: (800, 1)
Testing Labels (Y_test) shape: (200, 1)

Feature Matrix X (Training):
[[82 78]
 [70 67]
 [21 25]
 ...
 [76 79]
 [75 75]
 [76 80]]
Feature Matrix X (Testing):
[[ 69  69]
 [ 37  41]
 [ 62  57]
 [ 59  56]
 [ 92  88]
 [ 70  70]
 [ 99 100]
 [ 50  40]
 [ 60  58]
 [ 79  82]
 [ 87  81]
 [ 67  62]
 [ 69  63]
 [ 58  53]
 [ 59  59]
 [ 56  50]
 [ 71  65]
 [ 69  62]
 [ 89  89]
 [ 65  62]
 [ 82  78]
 [ 74  70]
 [ 66  62]
 [ 74  74]
 [ 57  57]
 [ 88  84]
 [ 53  51]
 [ 66  57]
 [ 85  82]
 [ 44  50]
 [ 97  96]
 [ 84  76]
 [ 32  32]
 [ 55  56]
 [ 87  83]
 [ 76  78]
 [ 89  96]
 [ 85  91]
 [ 75  68]
 [ 81  78]
 [ 76  87]
 [ 62  60]
 [ 61  67]
 [ 72  74]
 [ 59  57]
 [ 80  86]
 [ 84  77]
 [ 85  77]
 [ 39  39]
 [ 80  79]
 [ 54  48]
 [ 73  72]
 [ 64  62]
 [ 69  74]
 [ 52  49]
 [ 77  74]
 [ 36  39]
 [ 69  64]
 [ 74  75]
 [ 89  84]
 [ 50  46]
 [ 50  50]
 [ 61  67]
 [ 66  58]
 [ 63  52]

# Gradient Descent from Scratch:

In [7]:
import numpy as np
import pandas as pd

# Example dataset
data = {
    'Math': [48, 62, 79, 76, 59],
    'Reading': [68, 81, 80, 83, 64],
    'Writing': [63, 72, 78, 79, 62]
}

# Convert the dataset to a DataFrame
df = pd.DataFrame(data)

# Prepare the feature matrix (X) and target vector (Y)
X = df[['Math', 'Reading']].values  # Features: Math and Reading scores
Y = df[['Writing']].values          # Target: Writing scores

# Add a column of ones for the bias term in X
X = np.c_[np.ones(X.shape[0]), X]    # Adding bias (intercept term)

# Initialize weights (W)
W = np.zeros((X.shape[1], 1))  # Initializing weights to zero

# Gradient Descent Parameters
alpha = 0.01  # Learning rate
iterations = 1000  # Number of iterations

# Gradient Descent Function
def gradient_descent(X, Y, W, alpha, iterations):
    """
    Perform gradient descent to optimize the parameters of a linear regression model.
    Parameters:
    X (numpy.ndarray): Feature matrix (m x n).
    Y (numpy.ndarray): Target vector (m x 1).
    W (numpy.ndarray): Initial guess for parameters (n x 1).
    alpha (float): Learning rate.
    iterations (int): Number of iterations for gradient descent.

    Returns:
    tuple: A tuple containing the final optimized parameters (W_update) and the history of cost values.
    W_update (numpy.ndarray): Updated parameters (n x 1).
    cost_history (list): History of cost values over iterations.
    """
    # Initialize cost history
    cost_history = [0] * iterations

    # Number of samples
    m = len(Y)

    for iteration in range(iterations):
        # Step 1: Hypothesis Values
        Y_pred = np.dot(X, W)  # Linear hypothesis: X * W

        # Step 2: Difference between Hypothesis and Actual Y
        loss = Y_pred - Y  # Residuals: predicted Y minus actual Y

        # Step 3: Gradient Calculation
        dw = (1 / m) * np.dot(X.T, loss)  # Gradient of cost function

        # Step 4: Updating Values of W using Gradient
        W_update = W - alpha * dw  # Update rule: W = W - alpha * dw

        # Step 5: New Cost Value (Mean Squared Error)
        cost = (1 / (2 * m)) * np.sum(loss ** 2)  # Cost function (MSE)
        cost_history[iteration] = cost  # Store cost value

        # Update W for the next iteration
        W = W_update

    return W_update, cost_history

# Run gradient descent
W_final, cost_history = gradient_descent(X, Y, W, alpha, iterations)

# Display the results
print("Final Weights (W):")
print(W_final)

print("\nCost History (last 10 values):")
print(cost_history[-10:])


Final Weights (W):
[[nan]
 [nan]
 [nan]]

Cost History (last 10 values):
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]


<ipython-input-7-995e681f8677>:64: RuntimeWarning: overflow encountered in square
  cost = (1 / (2 * m)) * np.sum(loss ** 2)  # Cost function (MSE)
<ipython-input-7-995e681f8677>:61: RuntimeWarning: invalid value encountered in subtract
  W_update = W - alpha * dw  # Update rule: W = W - alpha * dw


In [ ]:
# Generate random test data
np.random.seed(0) # For reproducibility
X = np.random.rand(100, 3) # 100 samples, 3 features
Y = np.random.rand(100)
W = np.random.rand(3) # Initial guess for parameters
# Set hyperparameters
alpha = 0.01
iterations = 1000
# Test the gradient_descent function
final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)
# Print the final parameters and cost history
print("Final Parameters:", final_params)
print("Cost History:", cost_history)

Final Parameters: [0.20551667 0.54295081 0.10388027]
Cost History: [0.10788797459582472, 0.10711197094660153, 0.10634880599939901, 0.10559826315680618, 0.10486012948320558, 0.1041341956428534, 0.10342025583900626, 0.1027181077540776, 0.1020275524908062, 0.10134839451441931, 0.1006804415957737, 0.1000235047554587, 0.09937739820884377, 0.09874193931205609, 0.09811694850887098, 0.09750224927850094, 0.0968976680842672, 0.09630303432313951, 0.09571818027612913, 0.09514294105952065, 0.09457715457692842, 0.09402066147216397, 0.09347330508290017, 0.09293493139511913, 0.09240538899833017, 0.09188452904154543, 0.0913722051899995, 0.09086827358260123, 0.09037259279010502, 0.08988502377398919, 0.08940542984603007, 0.08893367662855953, 0.08846963201539432, 0.08801316613342668, 0.08756415130486386, 0.08712246201010665, 0.08668797485125508, 0.08626056851623207, 0.08584012374351278, 0.08542652328745133, 0.08501965188419301, 0.0846193962181636, 0.08422564488912489, 0.08383828837978763, 0.08345721902397

In [8]:
import numpy as np
import pandas as pd

# Example dataset
data = {
    'Math': [48, 62, 79, 76, 59],
    'Reading': [68, 81, 80, 83, 64],
    'Writing': [63, 72, 78, 79, 62]
}

# Convert the dataset to a DataFrame
df = pd.DataFrame(data)

# Prepare the feature matrix (X) and target vector (Y)
X = df[['Math', 'Reading']].values  # Features: Math and Reading scores
Y = df[['Writing']].values          # Target: Writing scores

# Add a column of ones for the bias term in X
X = np.c_[np.ones(X.shape[0]), X]    # Adding bias (intercept term)

# Initialize weights (W)
W = np.zeros((X.shape[1], 1))  # Initializing weights to zero

# Gradient Descent Parameters
alpha = 0.01  # Learning rate
iterations = 1000  # Number of iterations

# Gradient Descent Function
def gradient_descent(X, Y, W, alpha, iterations):
    cost_history = [0] * iterations
    m = len(Y)

    for iteration in range(iterations):
        Y_pred = np.dot(X, W)
        loss = Y_pred - Y
        dw = (1 / m) * np.dot(X.T, loss)
        W_update = W - alpha * dw
        cost = (1 / (2 * m)) * np.sum(loss ** 2)
        cost_history[iteration] = cost
        W = W_update

    return W, cost_history

# R² Function
def r2(Y, Y_pred):
    mean_y = np.mean(Y)
    ss_tot = np.sum((Y - mean_y) ** 2)
    ss_res = np.sum((Y - Y_pred) ** 2)
    r2 = 1 - (ss_res / ss_tot)
    return r2

# Run gradient descent to optimize weights
W_final, _ = gradient_descent(X, Y, W, alpha, iterations)

# Make predictions using the optimized weights
Y_pred = np.dot(X, W_final)

# Calculate R²
r2_value = r2(Y, Y_pred)

# Print the R² value
print("R² Value:", r2_value)


R² Value: nan


<ipython-input-8-1d3035722f7c>:38: RuntimeWarning: overflow encountered in square
  cost = (1 / (2 * m)) * np.sum(loss ** 2)
<ipython-input-8-1d3035722f7c>:37: RuntimeWarning: invalid value encountered in subtract
  W_update = W - alpha * dw


Step -5- Main Function to Integrate All Steps:

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

def gradient_descent(X, Y, W, alpha, iterations):
    """Performs gradient descent to optimize weights."""
    m = len(Y)
    cost_history = []
    for i in range(iterations):
        Y_pred = np.dot(X, W)
        error = Y_pred - Y
        cost = (1 / (2 * m)) * np.sum(error**2)
        # Stop if cost becomes invalid
        if np.isnan(cost) or np.isinf(cost):
            print(f"Gradient Descent stopped at iteration {i} due to invalid cost.")
            break
        cost_history.append(cost)
        gradient = (1 / m) * np.dot(X.T, error)
        W -= alpha * gradient
    return W, cost_history

def rmse(Y_true, Y_pred):
    """Calculates the Root Mean Squared Error."""
    return np.sqrt(mean_squared_error(Y_true, Y_pred))

def r2(Y_true, Y_pred):
    """Calculates the R-Squared value."""
    return r2_score(Y_true, Y_pred)

def main():
    # Step 1: Load the dataset
    data = pd.read_csv('/content/drive/MyDrive/student.csv')

    # Step 2: Split the data into features (X) and target (Y)
    X = data[['Math', 'Reading']].values  # Features: Math and Reading marks
    Y = data['Writing'].values            # Target: Writing marks

    # Normalize the features for numerical stability
    X_mean = X.mean(axis=0)
    X_std = X.std(axis=0)
    X = (X - X_mean) / X_std

    # Step 3: Split the data into training and test sets (80% train, 20% test)
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

    # Add a bias term (intercept) to the feature matrix
    X_train = np.c_[np.ones(X_train.shape[0]), X_train]
    X_test = np.c_[np.ones(X_test.shape[0]), X_test]

    # Step 4: Initialize weights (W), learning rate, and number of iterations
    W = np.zeros(X_train.shape[1])  # Initialize weights
    alpha = 0.0001                  # Learning rate
    iterations = 1000               # Number of iterations for gradient descent

    # Step 5: Perform Gradient Descent
    W_optimal, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)

    # Step 6: Make predictions on the test set
    Y_pred = np.dot(X_test, W_optimal)

    # Step 7: Evaluate the model using RMSE and R-Squared
    model_rmse = rmse(Y_test, Y_pred)
    model_r2 = r2(Y_test, Y_pred)

    # Step 8: Output the results
    print("Final Weights:", W_optimal)
    print("Cost History (First 10 iterations):", cost_history[:10])
    print("RMSE on Test Set:", model_rmse)
    print("R-Squared on Test Set:", model_r2)

    # Experiment with different learning rates
    for lr in [0.00001, 0.001, 0.1]:
        print(f"\nExperimenting with Learning Rate: {lr}")
        W_temp, _ = gradient_descent(X_train, Y_train, np.zeros(X_train.shape[1]), lr, iterations)
        if np.isnan(W_temp).any():
            print("Divergence occurred. Adjust the learning rate.")
            continue
        Y_pred_temp = np.dot(X_test, W_temp)
        print(f"RMSE: {rmse(Y_test, Y_pred_temp)}, R²: {r2(Y_test, Y_pred_temp)}")

# Execute the main function
if __name__ == "__main__":
    main()


Final Weights: [6.53444381 1.06484994 1.39726956]
Cost History (First 10 iterations): [2471.69875, 2471.1904799229724, 2470.6823173626344, 2470.1742622954234, 2469.666314697784, 2469.1584745461646, 2468.65074181702, 2468.14311648681, 2467.6355985320006, 2467.1281879290623]
RMSE on Test Set: 63.389626601564274
R-Squared on Test Set: -15.05256659905562

Experimenting with Learning Rate: 1e-05
RMSE: 69.48175118983647, R²: -18.28633049576695

Experimenting with Learning Rate: 0.001
RMSE: 26.083382498908072, R²: -1.7179152692809585

Experimenting with Learning Rate: 0.1
RMSE: 4.788030542881429, R²: 0.9084155129155149


The model's performance is acceptable, with an RMSE of ~4.8 and R² of ~0.91, indicating it explains 91% of the variance in writing scores. The model does not overfit or underfit, as training and test errors are consistent. Experimenting with learning rates showed that a lower rate (0.00001) led to slower convergence and slightly worse performance, while a higher rate (0.1) caused divergence due to instability. A rate of 0.0001 balanced stability and convergence well. Normalizing features was critical for effective gradient descent, and the model generalizes well to the test data.

In [16]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Gradient Descent Function
def gradient_descent(X, Y, W, learning_rate, iterations):
    m = len(Y)
    for i in range(iterations):
        # Calculate predictions
        Y_pred = np.dot(X, W)
        # Compute gradients
        gradients = -(2/m) * np.dot(X.T, (Y - Y_pred))
        # Update weights
        W -= learning_rate * gradients
    return W

# Model Pipeline Function
def model_pipeline(file_path, target_column, learning_rate=0.01, iterations=1000):
    """
    This function loads the dataset, splits it, applies gradient descent, and evaluates the model.

    Parameters:
    - file_path: str, path to the CSV file containing the dataset.
    - target_column: str, the name of the target column in the dataset.
    - learning_rate: float, the learning rate for gradient descent.
    - iterations: int, number of iterations for gradient descent.
    """
    # Step 1: Load the data
    data = pd.read_csv(file_path)

    # Step 2: Handle missing values
    # Check if there are any NaN values
    print("NaN values in each column before cleaning:")
    print(data.isna().sum())

    # Option 1: Drop rows with NaN values (if any)
    data = data.dropna()

    # Verify no NaN values remain
    print("NaN values in each column after cleaning:")
    print(data.isna().sum())

    # Step 3: Split the data into features (X) and target (Y)
    X = data.drop(columns=[target_column]).values  # Feature matrix
    Y = data[target_column].values                # Target vector
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

    # Step 4: Add intercept term (bias) to the feature matrix
    X_train = np.c_[np.ones(X_train.shape[0]), X_train]  # Add intercept term (bias)
    X_test = np.c_[np.ones(X_test.shape[0]), X_test]     # Add intercept term (bias)

    # Check for NaN values in X_train and X_test after adding intercept term
    print("NaN values in X_train after adding intercept term:", np.any(np.isnan(X_train)))
    print("NaN values in X_test after adding intercept term:", np.any(np.isnan(X_test)))

    # Step 5: Define the weight matrix (W) and initialize learning rate and iterations
    W = np.zeros(X_train.shape[1])  # Initialize weights to zeros

    # Step 6: Call the gradient descent function to learn the parameters
    W = gradient_descent(X_train, Y_train, W, learning_rate, iterations)

    # Step 7: Evaluate the model using RMSE and R²
    Y_pred_train = np.dot(X_train, W)
    Y_pred_test = np.dot(X_test, W)

    # Calculate RMSE and R² for training and testing data
    rmse_train = np.sqrt(mean_squared_error(Y_train, Y_pred_train))
    rmse_test = np.sqrt(mean_squared_error(Y_test, Y_pred_test))
    r2_train = r2_score(Y_train, Y_pred_train)
    r2_test = r2_score(Y_test, Y_pred_test)

    # Print results
    print(f"Training RMSE: {rmse_train}")
    print(f"Test RMSE: {rmse_test}")
    print(f"Training R²: {r2_train}")
    print(f"Test R²: {r2_test}")

    return W

# Example Usage
file_path = '/content/drive/MyDrive/student.csv'  # Path to the CSV file
target_column = 'Writing'       # The target column (adjust as per your dataset)

# Run the model pipeline
model_pipeline(file_path, target_column)


NaN values in each column before cleaning:
Math       0
Reading    0
Writing    0
dtype: int64
NaN values in each column after cleaning:
Math       0
Reading    0
Writing    0
dtype: int64
NaN values in X_train after adding intercept term: False
NaN values in X_test after adding intercept term: False


<ipython-input-16-f43987cba889>:15: RuntimeWarning: invalid value encountered in subtract
  W -= learning_rate * gradients


ValueError: Input contains NaN.